### ISSUE TITLE
Adopt Unified Addresses

### ISSUE THREAD

**Issue by LukasKorba** [zcash/secant-ios-wallet#514] opened 2023-01-04 12:43 UTC
Extend the secant app with the UAs.

**Comment by pacu** [comment] 2023-01-04 18:55
I think this is a duplicate of
https://app.zenhub.com/workspaces/wallet-5db8aa0244512d0001e0968e/issues/gh/zcash/secant-ios-wallet/74

**Closed** 2023-01-05 19:07 UTC
